/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  courseSidebar: [
    "index",
    {
      type: "category",
      label: "🚀 Start Here",
      collapsed: false,
      items: [
        "intro/quick-experience",
        "intro/environment-setup",
        "intro/ai-fullstack-map",
        "intro/learning-path",
      ],
    },
    {
      type: "category",
      label: "Main Track 1: Foundations (1-3)",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "1 Developer Tools Foundations",
          collapsed: true,
          link: { type: "doc", id: "ch01-tools/index" },
          items: [
            {
              type: "category",
              label: "1.1 Terminal and Command Line",
              items: [
                "ch01-tools/ch01-terminal/why-cli",
                "ch01-tools/ch01-terminal/basic-operations",
                "ch01-tools/ch01-terminal/package-managers",
              ],
            },
            {
              type: "category",
              label: "1.2 Git and Version Control",
              items: [
                "ch01-tools/ch02-git/git-basics",
                "ch01-tools/ch02-git/core-operations",
                "ch01-tools/ch02-git/remote-repos",
                "ch01-tools/ch02-git/branches",
              ],
            },
            {
              type: "category",
              label: "1.3 Development Environment Setup",
              items: [
                "ch01-tools/ch03-devenv/python-env",
                "ch01-tools/ch03-devenv/vscode",
                "ch01-tools/ch03-devenv/jupyter",
              ],
            },
            {
              type: "category",
              label: "1.4 Hands-on Workshop",
              items: [
                "ch01-tools/ch04-workshop/hands-on-tools-workshop",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "2 Python Programming Foundations",
          collapsed: true,
          link: { type: "doc", id: "ch02-python/index" },
          items: [
            "ch02-python/study-guide",
            {
              type: "category",
              label: "2.1 Python Language Basics",
              items: [
                "ch02-python/ch01-basics/intro",
                "ch02-python/ch01-basics/data-types",
                "ch02-python/ch01-basics/operators",
                "ch02-python/ch01-basics/io",
                "ch02-python/ch01-basics/control-flow",
                "ch02-python/ch01-basics/data-structures",
                "ch02-python/ch01-basics/functions",
                "ch02-python/ch01-basics/modules",
              ],
            },
            {
              type: "category",
              label: "2.2 Intermediate Python",
              items: [
                "ch02-python/ch02-advanced/oop",
                "ch02-python/ch02-advanced/exceptions",
                "ch02-python/ch02-advanced/file-io",
                "ch02-python/ch02-advanced/functional",
                "ch02-python/ch02-advanced/iterators-generators",
                "ch02-python/ch02-advanced/type-hints",
              ],
            },
            {
              type: "category",
              label: "2.3 Stage Projects",
              items: [
                "ch02-python/ch03-projects/todo-cli",
                "ch02-python/ch03-projects/web-scraper",
                "ch02-python/ch03-projects/web-api",
                "ch02-python/ch03-projects/ai-api-experience",
                "ch02-python/ch03-projects/hands-on-python-workshop",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "3 Data Analysis and Visualization",
          collapsed: true,
          link: { type: "doc", id: "ch03-data-analysis/index" },
          items: [
            "ch03-data-analysis/study-guide",
            {
              type: "category",
              label: "3.1 From Python to Data Analysis",
              items: ["ch03-data-analysis/ch01-warmup/pure-python-data"],
            },
            {
              type: "category",
              label: "3.2 NumPy Scientific Computing",
              items: [
                "ch03-data-analysis/ch02-numpy/overview",
                "ch03-data-analysis/ch02-numpy/array-basics",
                "ch03-data-analysis/ch02-numpy/indexing-slicing",
                "ch03-data-analysis/ch02-numpy/operations",
                "ch03-data-analysis/ch02-numpy/reshaping",
                "ch03-data-analysis/ch02-numpy/linear-algebra",
                "ch03-data-analysis/ch02-numpy/random-stats",
              ],
            },
            {
              type: "category",
              label: "3.3 Pandas Data Processing",
              items: [
                "ch03-data-analysis/ch03-pandas/roadmap",
                "ch03-data-analysis/ch03-pandas/core-structures",
                "ch03-data-analysis/ch03-pandas/read-write",
                "ch03-data-analysis/ch03-pandas/selection-filter",
                "ch03-data-analysis/ch03-pandas/data-cleaning",
                "ch03-data-analysis/ch03-pandas/data-transform",
                "ch03-data-analysis/ch03-pandas/groupby",
                "ch03-data-analysis/ch03-pandas/merge",
                "ch03-data-analysis/ch03-pandas/time-series",
              ],
            },
            {
              type: "category",
              label: "3.4 Data Visualization",
              items: [
                "ch03-data-analysis/ch04-visualization/roadmap",
                "ch03-data-analysis/ch04-visualization/matplotlib",
                "ch03-data-analysis/ch04-visualization/seaborn",
                "ch03-data-analysis/ch04-visualization/plotly",
                "ch03-data-analysis/ch04-visualization/best-practices",
              ],
            },
            {
              type: "category",
              label: "3.5 Database Basics (Elective)",
              items: [
                "ch03-data-analysis/ch05-database/roadmap",
                "ch03-data-analysis/ch05-database/relational-db",
                "ch03-data-analysis/ch05-database/sql-basics",
                "ch03-data-analysis/ch05-database/python-db",
                "ch03-data-analysis/ch05-database/db-design",
              ],
            },
            {
              type: "category",
              label: "3.6 Stage Projects",
              items: [
                "ch03-data-analysis/ch06-projects/eda-project",
                "ch03-data-analysis/ch06-projects/multi-source-analysis",
                "ch03-data-analysis/ch06-projects/hands-on-data-workshop",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Main Track 2: Understand Models (4-6)",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "4 Minimal Math Foundations for AI",
          collapsed: true,
          link: { type: "doc", id: "ch04-ai-math/index" },
          items: [
            "ch04-ai-math/study-guide",
            {
              type: "category",
              label: "4.1 Linear Algebra in Practice",
              items: [
                "ch04-ai-math/ch01-linear-algebra/roadmap",
                "ch04-ai-math/ch01-linear-algebra/vectors",
                "ch04-ai-math/ch01-linear-algebra/matrices",
                "ch04-ai-math/ch01-linear-algebra/eigenvalues",
                "ch04-ai-math/ch01-linear-algebra/vector-spaces",
              ],
            },
            {
              type: "category",
              label: "4.2 Probability and Statistics in Practice",
              items: [
                "ch04-ai-math/ch02-probability/roadmap",
                "ch04-ai-math/ch02-probability/probability-basics",
                "ch04-ai-math/ch02-probability/distributions",
                "ch04-ai-math/ch02-probability/statistical-inference",
                "ch04-ai-math/ch02-probability/information-theory",
                "ch04-ai-math/ch02-probability/history-foundations",
              ],
            },
            {
              type: "category",
              label: "4.3 Calculus and Optimization in Practice",
              items: [
                "ch04-ai-math/ch03-calculus/roadmap",
                "ch04-ai-math/ch03-calculus/derivatives",
                "ch04-ai-math/ch03-calculus/partial-derivatives-gradient",
                "ch04-ai-math/ch03-calculus/gradient-descent",
                "ch04-ai-math/ch03-calculus/chain-rule-backprop",
              ],
            },
            "ch04-ai-math/hands-on-math-workshop",
          ],
        },
        {
          type: "category",
          label: "5 Machine Learning from Basics to Practice",
          collapsed: true,
          link: { type: "doc", id: "ch05-machine-learning/index" },
          items: [
            "ch05-machine-learning/study-guide",
            {
              type: "category",
              label: "5.1 Core Machine Learning Concepts",
              items: [
                "ch05-machine-learning/ch01-ml-basics/roadmap",
                "ch05-machine-learning/ch01-ml-basics/history-breakthroughs",
                "ch05-machine-learning/ch01-ml-basics/what-is-ml",
                "ch05-machine-learning/ch01-ml-basics/sklearn-intro",
                "ch05-machine-learning/ch01-ml-basics/sklearn-matplotlib-workshop",
                "ch05-machine-learning/ch01-ml-basics/math-to-ml-bridge",
              ],
            },
            {
              type: "category",
              label: "5.2 Core Supervised Learning Algorithms",
              items: [
                "ch05-machine-learning/ch02-supervised/roadmap",
                "ch05-machine-learning/ch02-supervised/linear-regression",
                "ch05-machine-learning/ch02-supervised/logistic-regression",
                "ch05-machine-learning/ch02-supervised/decision-trees",
                "ch05-machine-learning/ch02-supervised/ensemble-learning",
                "ch05-machine-learning/ch02-supervised/svm",
              ],
            },
            {
              type: "category",
              label: "5.3 Unsupervised Learning Algorithms",
              items: [
                "ch05-machine-learning/ch03-unsupervised/roadmap",
                "ch05-machine-learning/ch03-unsupervised/clustering",
                "ch05-machine-learning/ch03-unsupervised/dimensionality-reduction",
                "ch05-machine-learning/ch03-unsupervised/anomaly-detection",
              ],
            },
            {
              type: "category",
              label: "5.4 Model Evaluation and Selection",
              items: [
                "ch05-machine-learning/ch04-evaluation/roadmap",
                "ch05-machine-learning/ch04-evaluation/metrics",
                "ch05-machine-learning/ch04-evaluation/cross-validation",
                "ch05-machine-learning/ch04-evaluation/bias-variance",
                "ch05-machine-learning/ch04-evaluation/hyperparameter-tuning",
              ],
            },
            {
              type: "category",
              label: "5.5 Feature Engineering",
              items: [
                "ch05-machine-learning/ch05-feature-engineering/roadmap",
                "ch05-machine-learning/ch05-feature-engineering/feature-understanding",
                "ch05-machine-learning/ch05-feature-engineering/preprocessing",
                "ch05-machine-learning/ch05-feature-engineering/feature-construction",
                "ch05-machine-learning/ch05-feature-engineering/feature-selection",
                "ch05-machine-learning/ch05-feature-engineering/pipeline",
              ],
            },
            {
              type: "category",
              label: "5.6 Stage Projects",
              items: [
                "ch05-machine-learning/ch06-projects/roadmap",
                "ch05-machine-learning/ch06-projects/house-price",
                "ch05-machine-learning/ch06-projects/customer-churn",
                "ch05-machine-learning/ch06-projects/user-segmentation",
                "ch05-machine-learning/ch06-projects/kaggle",
                "ch05-machine-learning/ch06-projects/hands-on-ml-workshop",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "6 Deep Learning and Transformer Foundations",
          collapsed: true,
          link: { type: "doc", id: "ch06-deep-learning/index" },
          items: [
            "ch06-deep-learning/study-guide",
            {
              type: "category",
              label: "6.1 Neural Network Foundations",
              items: [
                "ch06-deep-learning/ch01-nn-basics/roadmap",
                "ch06-deep-learning/ch01-nn-basics/history-breakthroughs",
                "ch06-deep-learning/ch01-nn-basics/ml-to-dl-bridge",
                "ch06-deep-learning/ch01-nn-basics/neurons-activation",
                "ch06-deep-learning/ch01-nn-basics/forward-backward",
                "ch06-deep-learning/ch01-nn-basics/optimizers",
                "ch06-deep-learning/ch01-nn-basics/regularization",
                "ch06-deep-learning/ch01-nn-basics/weight-init",
              ],
            },
            {
              type: "category",
              label: "6.2 PyTorch Framework",
              items: [
                "ch06-deep-learning/ch02-pytorch/roadmap",
                "ch06-deep-learning/ch02-pytorch/sklearn-to-pytorch-bridge",
                "ch06-deep-learning/ch02-pytorch/pytorch-basics",
                "ch06-deep-learning/ch02-pytorch/autograd",
                "ch06-deep-learning/ch02-pytorch/nn-module",
                "ch06-deep-learning/ch02-pytorch/data-loading",
                "ch06-deep-learning/ch02-pytorch/training-loop",
                "ch06-deep-learning/ch02-pytorch/practical-tips",
                "ch06-deep-learning/ch02-pytorch/pytorch-matplotlib-workshop",
              ],
            },
            {
              type: "category",
              label: "6.3-6.4 CNN, RNN, and Sequence Models",
              items: [
                "ch06-deep-learning/ch03-cnn/roadmap",
                "ch06-deep-learning/ch03-cnn/convolution-basics",
                "ch06-deep-learning/ch03-cnn/cnn-structure",
                "ch06-deep-learning/ch03-cnn/classic-architectures",
                "ch06-deep-learning/ch03-cnn/transfer-learning",
                "ch06-deep-learning/ch03-cnn/image-classification-practice",
                "ch06-deep-learning/ch04-rnn/roadmap",
                "ch06-deep-learning/ch04-rnn/rnn-basics",
                "ch06-deep-learning/ch04-rnn/lstm-gru",
                "ch06-deep-learning/ch04-rnn/sequence-practice",
              ],
            },
            {
              type: "category",
              label: "6.5 Attention and Transformer",
              items: [
                "ch06-deep-learning/ch05-transformer/roadmap",
                "ch06-deep-learning/ch05-transformer/attention-mechanism",
                "ch06-deep-learning/ch05-transformer/transformer-architecture",
              ],
            },
            {
              type: "category",
              label: "6.6-6.7 Generative Models and Training Tips (Elective)",
              items: [
                "ch06-deep-learning/ch06-generative/roadmap",
                "ch06-deep-learning/ch06-generative/gan",
                "ch06-deep-learning/ch06-generative/vae",
                "ch06-deep-learning/ch07-training-tips/roadmap",
                "ch06-deep-learning/ch07-training-tips/hyperparameter-tuning",
                "ch06-deep-learning/ch07-training-tips/training-diagnosis",
                "ch06-deep-learning/ch07-training-tips/model-compression",
              ],
            },
            {
              type: "category",
              label: "6.8 Stage Projects",
              items: [
                "ch06-deep-learning/ch08-projects/roadmap",
                "ch06-deep-learning/ch08-projects/image-classification",
                "ch06-deep-learning/ch08-projects/sentiment-analysis",
                "ch06-deep-learning/ch08-projects/generative-practice",
                "ch06-deep-learning/ch08-projects/hands-on-dl-workshop",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Main Track 3: Build LLM Applications (7-9)",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "7 LLM Principles, Prompting, and Fine-Tuning",
          collapsed: true,
          link: { type: "doc", id: "ch07-llm-principles/index" },
          items: [
            "ch07-llm-principles/study-guide",
            {
              type: "category",
              label: "7.1-7.2 NLP and LLM Crash Course",
              items: [
                "ch07-llm-principles/ch01-nlp-crash/roadmap",
                "ch07-llm-principles/ch01-nlp-crash/tokenizer",
                "ch07-llm-principles/ch01-nlp-crash/embeddings",
                "ch07-llm-principles/ch01-nlp-crash/pretrained-models",
                "ch07-llm-principles/ch01-nlp-crash/huggingface-quickstart",
                "ch07-llm-principles/ch01-nlp-crash/tokenizer-embedding-lab",
                "ch07-llm-principles/ch02-llm-overview/roadmap",
                "ch07-llm-principles/ch02-llm-overview/development-history",
                "ch07-llm-principles/ch02-llm-overview/core-concepts",
                "ch07-llm-principles/ch02-llm-overview/industry-landscape",
                "ch07-llm-principles/ch02-llm-overview/llm-call-workbench",
              ],
            },
            {
              type: "category",
              label: "7.3-7.4 Transformer and Pretraining",
              items: [
                "ch07-llm-principles/ch03-transformer-deep/roadmap",
                "ch07-llm-principles/ch03-transformer-deep/architecture-review",
                "ch07-llm-principles/ch03-transformer-deep/modern-decoder-block",
                "ch07-llm-principles/ch03-transformer-deep/model-variants",
                "ch07-llm-principles/ch03-transformer-deep/efficient-attention",
                "ch07-llm-principles/ch03-transformer-deep/scale-computation",
                "ch07-llm-principles/ch04-pretraining/roadmap",
                "ch07-llm-principles/ch04-pretraining/pretraining-data",
                "ch07-llm-principles/ch04-pretraining/pretraining-methods",
                "ch07-llm-principles/ch04-pretraining/pretraining-engineering",
              ],
            },
            {
              type: "category",
              label: "7.5-7.7 Prompting, Fine-Tuning, and Alignment",
              items: [
                "ch07-llm-principles/ch05-prompt/roadmap",
                "ch07-llm-principles/ch05-prompt/prompt-basics",
                "ch07-llm-principles/ch05-prompt/advanced-prompting",
                "ch07-llm-principles/ch05-prompt/structured-output",
                "ch07-llm-principles/ch05-prompt/prompt-practice",
                "ch07-llm-principles/ch05-prompt/prompt-evaluation-lab",
                "ch07-llm-principles/ch06-finetuning/roadmap",
                "ch07-llm-principles/ch06-finetuning/finetuning-overview",
                "ch07-llm-principles/ch06-finetuning/lora-qlora",
                "ch07-llm-principles/ch06-finetuning/other-peft",
                "ch07-llm-principles/ch06-finetuning/finetuning-practice",
                "ch07-llm-principles/ch06-finetuning/data-labeling",
                "ch07-llm-principles/ch07-alignment/roadmap",
                "ch07-llm-principles/ch07-alignment/alignment-problem",
                "ch07-llm-principles/ch07-alignment/rlhf",
                "ch07-llm-principles/ch07-alignment/alternative-methods",
                "ch07-llm-principles/ch07-alignment/safety-evaluation-lab",
              ],
            },
            {
              type: "category",
              label: "7.8 Stage Project",
              items: [
                "ch07-llm-principles/ch08-projects/roadmap",
                "ch07-llm-principles/ch08-projects/domain-finetuning",
                "ch07-llm-principles/ch08-projects/deliverables-kit",
                "ch07-llm-principles/ch08-projects/stage-hands-on-workshop",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "8 LLM Application Development and RAG",
          collapsed: true,
          link: { type: "doc", id: "ch08-rag/index" },
          items: [
            "ch08-rag/study-guide",
            "ch08-rag/task-list",
            {
              type: "category",
              label: "8.1 RAG: Retrieval-Augmented Generation",
              items: [
                "ch08-rag/ch01-rag/roadmap",
                "ch08-rag/ch01-rag/rag-basics",
                "ch08-rag/ch01-rag/document-processing",
                "ch08-rag/ch01-rag/vector-databases",
                "ch08-rag/ch01-rag/retrieval-strategies",
                "ch08-rag/ch01-rag/rag-optimization",
                "ch08-rag/ch01-rag/advanced-rag",
                "ch08-rag/ch01-rag/rag-evaluation",
              ],
            },
            {
              type: "category",
              label: "8.2 Model Deployment and Unified APIs",
              items: [
                "ch08-rag/ch02-deployment/roadmap",
                "ch08-rag/ch02-deployment/local-models",
                "ch08-rag/ch02-deployment/inference-servers",
                "ch08-rag/ch02-deployment/unified-api",
              ],
            },
            {
              type: "category",
              label: "8.3 LLM Application Development",
              items: [
                "ch08-rag/ch03-app-dev/roadmap",
                "ch08-rag/ch03-app-dev/llm-api-practice",
                "ch08-rag/ch03-app-dev/langchain-basics",
                "ch08-rag/ch03-app-dev/function-calling",
                "ch08-rag/ch03-app-dev/huggingface-deep",
                "ch08-rag/ch03-app-dev/dialog-system",
                "ch08-rag/ch03-app-dev/ai-assisted-coding",
                "ch08-rag/ch03-app-dev/document-parsing",
                "ch08-rag/ch03-app-dev/template-doc-generation",
              ],
            },
            {
              type: "category",
              label: "8.4-8.5 Engineering and Stage Project",
              items: [
                "ch08-rag/ch04-engineering/roadmap",
                "ch08-rag/ch04-engineering/async-programming",
                "ch08-rag/ch04-engineering/api-design",
                "ch08-rag/ch04-engineering/logging-monitoring",
                "ch08-rag/ch04-engineering/docker-deployment",
                "ch08-rag/ch05-projects/roadmap",
                "ch08-rag/ch05-projects/enterprise-kb",
                "ch08-rag/ch05-projects/domain-rag-finetuning",
                "ch08-rag/ch05-projects/intelligent-assistant",
                "ch08-rag/ch05-projects/courseware-assistant",
                "ch08-rag/ch05-projects/stage-hands-on-workshop",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "9 AI Agents and Agentic Systems",
          collapsed: true,
          link: { type: "doc", id: "ch09-agent/index" },
          items: [
            "ch09-agent/study-guide",
            "ch09-agent/task-list",
            {
              type: "category",
              label: "9.1-9.2 Agent Basics, Reasoning, and Planning",
              items: [
                "ch09-agent/ch01-agent-basics/roadmap",
                "ch09-agent/ch01-agent-basics/what-is-agent",
                "ch09-agent/ch01-agent-basics/development-history",
                "ch09-agent/ch01-agent-basics/capability-levels",
                "ch09-agent/ch01-agent-basics/system-architecture",
                "ch09-agent/ch01-agent-basics/rl-to-agent-breakthroughs",
                "ch09-agent/ch02-reasoning/roadmap",
                "ch09-agent/ch02-reasoning/llm-reasoning",
                "ch09-agent/ch02-reasoning/chain-reasoning",
                "ch09-agent/ch02-reasoning/react",
                "ch09-agent/ch02-reasoning/plan-and-execute",
                "ch09-agent/ch02-reasoning/advanced-planning",
                "ch09-agent/ch02-reasoning/reasoning-evaluation",
              ],
            },
            {
              type: "category",
              label: "9.3-9.5 Tools, Memory, and MCP",
              items: [
                "ch09-agent/ch03-tools/roadmap",
                "ch09-agent/ch03-tools/function-calling-deep",
                "ch09-agent/ch03-tools/tool-description",
                "ch09-agent/ch03-tools/tool-strategies",
                "ch09-agent/ch03-tools/common-tools",
                "ch09-agent/ch03-tools/tool-safety",
                "ch09-agent/ch03-tools/advanced-patterns",
                "ch09-agent/ch03-tools/code-agent",
                "ch09-agent/ch03-tools/multi-tool-practice",
                "ch09-agent/ch04-memory/roadmap",
                "ch09-agent/ch04-memory/memory-overview",
                "ch09-agent/ch04-memory/short-term-memory",
                "ch09-agent/ch04-memory/long-term-memory",
                "ch09-agent/ch04-memory/episodic-procedural",
                "ch09-agent/ch04-memory/memory-engineering",
                "ch09-agent/ch04-memory/memory-practice",
                "ch09-agent/ch05-mcp/roadmap",
                "ch09-agent/ch05-mcp/mcp-overview",
                "ch09-agent/ch05-mcp/mcp-architecture",
                "ch09-agent/ch05-mcp/mcp-server-dev",
                "ch09-agent/ch05-mcp/mcp-client-integration",
                "ch09-agent/ch05-mcp/mcp-ecosystem",
              ],
            },
            {
              type: "category",
              label: "9.6-9.9 Frameworks, Multi-Agent, and Production",
              items: [
                "ch09-agent/ch06-frameworks/roadmap",
                "ch09-agent/ch06-frameworks/framework-overview",
                "ch09-agent/ch06-frameworks/langchain-langgraph",
                "ch09-agent/ch06-frameworks/llamaindex",
                "ch09-agent/ch06-frameworks/crewai",
                "ch09-agent/ch06-frameworks/autogen",
                "ch09-agent/ch06-frameworks/openai-agents-sdk",
                "ch09-agent/ch06-frameworks/low-code-platforms",
                "ch09-agent/ch06-frameworks/framework-selection",
                "ch09-agent/ch07-multi-agent/roadmap",
                "ch09-agent/ch07-multi-agent/architecture-patterns",
                "ch09-agent/ch07-multi-agent/communication",
                "ch09-agent/ch07-multi-agent/task-coordination",
                "ch09-agent/ch07-multi-agent/practice-patterns",
                "ch09-agent/ch07-multi-agent/challenges",
                "ch09-agent/ch07-multi-agent/multi-agent-practice",
                "ch09-agent/ch08-eval-safety/roadmap",
                "ch09-agent/ch08-eval-safety/evaluation-methods",
                "ch09-agent/ch08-eval-safety/benchmarks",
                "ch09-agent/ch08-eval-safety/agent-security",
                "ch09-agent/ch08-eval-safety/guardrails",
                "ch09-agent/ch08-eval-safety/observability",
                "ch09-agent/ch09-deployment/roadmap",
                "ch09-agent/ch09-deployment/deployment-architecture",
                "ch09-agent/ch09-deployment/runtime-management",
                "ch09-agent/ch09-deployment/persistence-recovery",
                "ch09-agent/ch09-deployment/cost-optimization",
                "ch09-agent/ch09-deployment/production-best-practices",
              ],
            },
            {
              type: "category",
              label: "9.10 Stage Project",
              items: [
                "ch09-agent/ch10-projects/roadmap",
                "ch09-agent/ch10-projects/research-assistant",
                "ch09-agent/ch10-projects/data-analysis-agent",
                "ch09-agent/ch10-projects/multi-agent-dev-team",
                "ch09-agent/ch10-projects/stage-hands-on-workshop",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Main Track 4: Specializations and Capstone (10-12)",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "10 Computer Vision (Specialization Elective)",
          collapsed: true,
          link: { type: "doc", id: "ch10-computer-vision/index" },
          items: [
            "ch10-computer-vision/study-guide",
            "ch10-computer-vision/task-list",
            {
              type: "category",
              label: "10.1-10.2 CV Basics and Image Classification",
              items: [
                "ch10-computer-vision/ch01-cv-basics/roadmap",
                "ch10-computer-vision/ch01-cv-basics/image-fundamentals",
                "ch10-computer-vision/ch01-cv-basics/opencv-basics",
                "ch10-computer-vision/ch01-cv-basics/image-processing",
                "ch10-computer-vision/ch02-classification/roadmap",
                "ch10-computer-vision/ch02-classification/data-augmentation",
                "ch10-computer-vision/ch02-classification/modern-architectures",
                "ch10-computer-vision/ch02-classification/training-tricks",
              ],
            },
            {
              type: "category",
              label: "10.3-10.6 Detection, Segmentation, and Advanced Projects",
              items: [
                "ch10-computer-vision/ch03-detection/roadmap",
                "ch10-computer-vision/ch03-detection/detection-overview",
                "ch10-computer-vision/ch03-detection/classic-detectors",
                "ch10-computer-vision/ch03-detection/yolo-series",
                "ch10-computer-vision/ch03-detection/detection-practice",
                "ch10-computer-vision/ch04-segmentation/roadmap",
                "ch10-computer-vision/ch04-segmentation/semantic-segmentation",
                "ch10-computer-vision/ch04-segmentation/instance-segmentation",
                "ch10-computer-vision/ch04-segmentation/segmentation-practice",
                "ch10-computer-vision/ch05-advanced/roadmap",
                "ch10-computer-vision/ch05-advanced/face-detection",
                "ch10-computer-vision/ch05-advanced/video-analysis",
                "ch10-computer-vision/ch05-advanced/ocr",
                "ch10-computer-vision/ch05-advanced/04-3d-vision",
                "ch10-computer-vision/ch06-projects/roadmap",
                "ch10-computer-vision/ch06-projects/security-detection",
                "ch10-computer-vision/ch06-projects/medical-imaging",
                "ch10-computer-vision/ch06-projects/hands-on-vision-workshop",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "11 Natural Language Processing (Specialization Elective)",
          collapsed: true,
          link: { type: "doc", id: "ch11-nlp/index" },
          items: [
            "ch11-nlp/study-guide",
            "ch11-nlp/task-list",
            {
              type: "category",
              label: "11.1-11.6 NLP Basics to Pretrained Models",
              items: [
                "ch11-nlp/ch01-text-basics/roadmap",
                "ch11-nlp/ch01-text-basics/nlp-overview",
                "ch11-nlp/ch01-text-basics/text-preprocessing",
                "ch11-nlp/ch01-text-basics/text-representation",
                "ch11-nlp/ch02-embeddings/roadmap",
                "ch11-nlp/ch02-embeddings/word-embedding",
                "ch11-nlp/ch02-embeddings/contextual-embedding",
                "ch11-nlp/ch02-embeddings/language-models",
                "ch11-nlp/ch03-classification/roadmap",
                "ch11-nlp/ch03-classification/traditional-methods",
                "ch11-nlp/ch03-classification/deep-learning-methods",
                "ch11-nlp/ch03-classification/classification-practice",
                "ch11-nlp/ch04-sequence-labeling/roadmap",
                "ch11-nlp/ch04-sequence-labeling/hmm-crf-history",
                "ch11-nlp/ch04-sequence-labeling/ner-overview",
                "ch11-nlp/ch04-sequence-labeling/bilstm-crf",
                "ch11-nlp/ch04-sequence-labeling/ner-practice",
                "ch11-nlp/ch05-seq2seq/roadmap",
                "ch11-nlp/ch05-seq2seq/encoder-decoder",
                "ch11-nlp/ch05-seq2seq/attention-in-nlp",
                "ch11-nlp/ch05-seq2seq/machine-translation",
                "ch11-nlp/ch05-seq2seq/ctc-deep-speech",
                "ch11-nlp/ch06-pretrained/roadmap",
                "ch11-nlp/ch06-pretrained/pretrain-paradigm",
                "ch11-nlp/ch06-pretrained/bert",
                "ch11-nlp/ch06-pretrained/gpt-series",
                "ch11-nlp/ch06-pretrained/t5",
                "ch11-nlp/ch06-pretrained/transformers-library",
              ],
            },
            {
              type: "category",
              label: "11.7 NLP Capstone Project",
              items: [
                "ch11-nlp/ch07-projects/roadmap",
                "ch11-nlp/ch07-projects/qa-system",
                "ch11-nlp/ch07-projects/text-summarization",
                "ch11-nlp/ch07-projects/information-extraction",
                "ch11-nlp/ch07-projects/semantic-graphs-amr",
                "ch11-nlp/ch07-projects/hands-on-nlp-workshop",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "12 AIGC and Multimodal AI",
          collapsed: true,
          link: { type: "doc", id: "ch12-multimodal/index" },
          items: [
            "ch12-multimodal/study-guide",
            "ch12-multimodal/task-list",
            {
              type: "category",
              label: "12.1-12.3 Multimodal, Image, and Video Generation",
              items: [
                "ch12-multimodal/ch01-multimodal/roadmap",
                "ch12-multimodal/ch01-multimodal/multimodal-basics",
                "ch12-multimodal/ch01-multimodal/vision-language",
                "ch12-multimodal/ch01-multimodal/multimodal-apps",
                "ch12-multimodal/ch02-image-gen/roadmap",
                "ch12-multimodal/ch02-image-gen/diffusion-models",
                "ch12-multimodal/ch02-image-gen/stable-diffusion",
                "ch12-multimodal/ch02-image-gen/sd-applications",
                "ch12-multimodal/ch02-image-gen/sd-finetuning",
                "ch12-multimodal/ch02-image-gen/latest-progress",
                "ch12-multimodal/ch03-video-gen/roadmap",
                "ch12-multimodal/ch03-video-gen/video-generation",
                "ch12-multimodal/ch03-video-gen/tts",
                "ch12-multimodal/ch03-video-gen/digital-human",
              ],
            },
            {
              type: "category",
              label: "12.4-12.5 Frontiers, Ethics, and Projects",
              items: [
                "ch12-multimodal/ch04-frontier/roadmap",
                "ch12-multimodal/ch04-frontier/frontier-trends",
                "ch12-multimodal/ch04-frontier/ai-ethics",
                "ch12-multimodal/ch04-frontier/ai-regulations",
                "ch12-multimodal/ch05-projects/roadmap",
                "ch12-multimodal/ch05-projects/creative-platform",
                "ch12-multimodal/ch05-projects/hands-on-multimodal-workshop",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "📦 Elective Modules",
      collapsed: true,
      items: [
        "electives/hands-on-elective-workshop",
        {
          type: "category",
          label: "Module A: C++ and Model Deployment",
          link: { type: "doc", id: "electives/module-a/index" },
          items: [
            "electives/module-a/cpp-basics",
            "electives/module-a/cpp-advanced",
            "electives/module-a/model-optimization",
            "electives/module-a/inference-engines",
            "electives/module-a/edge-deployment",
            "electives/module-a/model-serving",
            "electives/module-a/projects",
          ],
        },
        {
          type: "category",
          label: "Module B: Advanced Python Topics",
          link: { type: "doc", id: "electives/module-b/index" },
          items: [
            "electives/module-b/decorators-advanced",
            "electives/module-b/iterators-advanced",
            "electives/module-b/concurrency",
            "electives/module-b/metaprogramming",
          ],
        },
        {
          type: "category",
          label: "Module C: Classic ML Supplementary Algorithms",
          link: { type: "doc", id: "electives/module-c/index" },
          items: [
            "electives/module-c/svm",
            "electives/module-c/knn",
            "electives/module-c/naive-bayes",
            "electives/module-c/lda",
          ],
        },
        "electives/module-d",
        "electives/module-e",
        "electives/module-f",
      ],
    },
    {
      type: "category",
      label: "📎 Appendix",
      collapsed: true,
      items: [
        "appendix/resources",
        "appendix/course-numbering",
        "appendix/ai-milestones",
        "appendix/visual-enhancement-plan",
        "appendix/hardware",
        "appendix/faq",
        "appendix/continuous-learning",
        "appendix/troubleshooting",
        "appendix/resource-quick-ref",
        "appendix/job-prep",
      ],
    },
  ],
};

module.exports = sidebars;
