#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const docsRoot = path.join(projectRoot, "src/content/docs");
const outputPath = path.join(projectRoot, "docker/00-legacy_redirect_map.conf");
const localesWithLegacyZhHans = new Set(["zh-cn"]);

const manualRedirects = new Map([
  ["/sitemap.html", "/sitemap.xml"],
  ["/zh-Hans/en", "/"],
  ["/zh-cn/en", "/"],
  ["/stage1/ch01-basics/data-types", "/ch02-python/ch01-basics/02-data-types/"],
  ["/stage3/ch02-probability/distributions", "/ch04-ai-math/ch02-probability/02-distributions/"],
  ["/stage4/ch04-evaluation/bias-variance", "/ch05-machine-learning/ch04-evaluation/03-bias-variance/"],
]);

function walkMarkdownFiles(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdownFiles(fullPath, files);
    } else if (/\.mdx?$/.test(entry.name)) {
      files.push(fullPath);
    }
  }
  return files;
}

function toPosix(relativePath) {
  return relativePath.split(path.sep).join("/");
}

function withTrailingSlash(route) {
  if (route === "/") return route;
  return route.endsWith("/") ? route : `${route}/`;
}

function withoutTrailingSlash(route) {
  if (route === "/") return route;
  return route.endsWith("/") ? route.slice(0, -1) : route;
}

function normalizeTarget(target) {
  if (target === "/") return target;
  if (path.posix.extname(withoutTrailingSlash(target))) {
    return withoutTrailingSlash(target);
  }
  return withTrailingSlash(target);
}

function routeFromDoc(filePath) {
  const rel = toPosix(path.relative(docsRoot, filePath));
  const parts = rel.split("/");
  const fileName = parts.pop();
  const stem = fileName.replace(/\.mdx?$/, "");

  if (stem !== "index") {
    parts.push(stem);
  }

  return withTrailingSlash(`/${parts.join("/")}`);
}

function stripNumberPrefix(segment) {
  return segment.replace(/^\d{2}-/, "");
}

function strippedNumberRoute(route) {
  const segments = withoutTrailingSlash(route).split("/").filter(Boolean);
  const stripped = segments.map(stripNumberPrefix);
  if (segments.join("/") === stripped.join("/")) return null;
  return withTrailingSlash(`/${stripped.join("/")}`);
}

function addRedirect(redirects, source, target) {
  const normalizedTarget = normalizeTarget(target);
  const sourceVariants = new Set([source, withTrailingSlash(source), withoutTrailingSlash(source)]);

  for (const sourceVariant of sourceVariants) {
    if (!sourceVariant || sourceVariant === normalizedTarget) continue;
    const existing = redirects.get(sourceVariant);
    if (existing && existing !== normalizedTarget) {
      throw new Error(`Conflicting legacy redirect for ${sourceVariant}: ${existing} vs ${normalizedTarget}`);
    }
    redirects.set(sourceVariant, normalizedTarget);
  }
}

function addRouteRedirects(redirects, route) {
  const stripped = strippedNumberRoute(route);
  if (stripped) {
    addRedirect(redirects, stripped, route);
  }

  const segments = withoutTrailingSlash(route).split("/").filter(Boolean);
  const locale = segments[0];
  if (localesWithLegacyZhHans.has(locale)) {
    const zhHansRoute = withTrailingSlash(`/${["zh-Hans", ...segments.slice(1)].join("/")}`);
    addRedirect(redirects, zhHansRoute, route);

    const zhHansStripped = strippedNumberRoute(zhHansRoute);
    if (zhHansStripped) {
      addRedirect(redirects, zhHansStripped, route);
    }
  }
}

function nginxEscape(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

const redirects = new Map();
for (const [source, target] of manualRedirects) {
  addRedirect(redirects, source, target);
}

for (const file of walkMarkdownFiles(docsRoot)) {
  addRouteRedirects(redirects, routeFromDoc(file));
}

const entries = [...redirects.entries()]
  .filter(([source]) => source !== "/")
  .sort(([a], [b]) => a.localeCompare(b));

const content = [
  "# Generated by scripts/generate_legacy_redirect_map.mjs. Do not edit by hand.",
  "# Keeps old unnumbered course URLs, legacy zh-Hans paths, and retired sitemap URLs indexable via 301 redirects.",
  "map_hash_bucket_size 512;",
  "map_hash_max_size 16384;",
  "map $uri $legacy_redirect_uri {",
  '  default "";',
  ...entries.map(([source, target]) => `  "${nginxEscape(source)}" "${nginxEscape(target)}";`),
  "}",
  "",
].join("\n");

fs.writeFileSync(outputPath, content);
console.log(`generate_legacy_redirect_map: wrote ${path.relative(projectRoot, outputPath)} (${entries.length} redirects)`);
